# Generated by Django 3.2.12 on 2023-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gukov_hw2', '0006_auto_20230620_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=686143),
        ),
    ]
