# Generated by Django 3.2.12 on 2023-06-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gukov_hw2', '0009_alter_like_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gukov_hw2.question'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=737282),
        ),
    ]
