# Generated by Django 3.2.12 on 2023-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gukov_hw2', '0010_auto_20230620_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=660493),
        ),
    ]
