# Generated by Django 3.2.12 on 2023-06-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gukov_hw2', '0015_alter_like_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=247271),
        ),
    ]
